name: generator_translation_disk
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch=1.11.0
  - cudatoolkit=11.3
  - uproot
  - awkward
  - h5py
  - matplotlib
  - jupyter
